# .github/workflows/release.yml
#checkov:skip=CKV_GHA_7:We build changelog manually for now
name: changelog

on:
  workflow_dispatch:
    inputs:
      from_tag:
        description: "Starting Tag"
        required: true
        type: string
      to_tag:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: ${{ github.event.inputs.from_tag }}
          toTag: ${{ github.event.inputs.to_tag }}
          configurationJson: |
            {
                "categories": [
                    {
                      "title": "## ğŸš€ Features",
                      "labels": ["feature","feat","Feature","Feat"]
                    },
                    {
                      "title": "## ğŸ› Fixes",
                      "labels": ["fix","fixes", "bug", "bugs", "Fix", "Fixes", "Bug", "Bugs"]
                    },
                    {
                      "title": "## ğŸ§ª Tests",
                      "labels": ["test", "tests", "Test", "Tests"]
                    },
                    {
                      "title": "## ğŸ“¦ Uncategorized",
                      "labels": []
                    }
                  ],
                "label_extractor": [
                    {
                        "pattern": "^.?(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|tests).?.*",
                        "target": "$1",
                        "method": "regexr",
                        "on_property": "title"
                    }
                ],
            }
      - name: Update Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          tag_name: ${{ github.event.inputs.to_tag }}
          body: ${{steps.github_release_changelog.outputs.changelog}}
